
{
    function declareUsersResources(pipTranslateProvider: pip.services.ITranslateProvider) {
        pipTranslateProvider.translations('en', {
            USERS: 'Accounts',
            ADMINISTRATION_USERS: 'Accounts',
            NEW_ACCOUNT: 'New accounts',
            USERS_EMPTY: 'Accounts were not found',
            ADD_USER: 'Add accounts',
            USER_SESSIONS_EMPTY: 'Sessions were not found',
            LOADING_PROGRESS_USER_SESSIONS: 'Loading sessions',

            USER_ACTIVITES_EMPTY: 'Activities were not found',
            LOADING_PROGRESS_USER_ACTIVITES: 'Loading activities',
            SETTING_SYSTEM_ACCOUNTS_ROLE: 'Access level',
            SETTING_SYSTEM_ACCOUNTS_ABOUT: 'Position',
            SETTINGS_SYSTEM_ACCOUNTS_INVITE: 'Invitation',
            SETTING_SYSTEM_ACCOUNTS_INVITE_TITLE: 'Inivitations',
            SETTING_SYSTEM_ACCOUNTS_INVITE_EMAIL: 'Email',
            SETTING_SYSTEM_ACCOUNTS_INVITE_TIME: 'Invite date',
            SETTING_SYSTEM_ACCOUNTS_INVITE_TITLE_RESPONSE: 'Response',
            SETTING_SYSTEM_ACCOUNTS_ADD: 'Add',
            RESEND: 'Resend',
            DELETE_INVITE: 'Delete invite',
            ACTIVATE_INVITE: 'Activate invite',
            DELETE_ROLE: 'Delete access',
            SETTINGS_SYSTEM_ACCOUNTS_INVITE_RESPONSE: 'response',
            REFUSE: 'Refuse',
            ACTIVATE: 'Activate',
            SETTING_SYSTEM_ACCOUNTS_INVITE_RESPONSE_FROM: 'From ',
            admin: 'Admin',
            manager: 'Manager',
            user: 'User',
            ADMIN_SUBTITLE: 'admin',
            MANAGER_SUBTITLE: 'manager',
            USER_SUBTITLE: 'user',
            SETTING_SYSTEM_ACCOUNTS_SEND: 'Send',
            INVITE_IS_FOUND1: 'User',
            INVITE_IS_FOUND: 'User already exists.',
            INVITE_IS_FOUND2: 'already exists.',
            ACCOUTNT_DELETE: 'Remove',
            USER_ID: 'System identifier',
            'SETTINGS_BASIC_INFO_FROM': 'User since ',
            'SETTINGS_ACTIVE_SESSIONS_CLOSE_SESSION': 'Close session',
            'SETTINGS_ACTIVE_SESSIONS_CLOSE_ACTIVE_SESSIONS': 'Close active sessions',
            'SETTINGS_ACTIVE_SESSION_OS': 'OS: ',
            'SETTINGS_ACTIVE_SESSION_IP': 'IP: ',
            'SETTINGS_ACTIVE_SESSION_ACTIVE': 'active',
            'SETTINGS_ACTIVE_SESSION_INACTIVE': 'inactive',
            LOADING_ACCOUNTS: 'Loading accounts...',
            ADMINISTRATION_USERS_DETAILS: 'User details',
            ADMINISTRATION_USERS_EDIT: 'Edit user',
            ADMINISTRATION_USERS_ADD: 'Add user',
            'INFORMATION': "Information",

        });
        pipTranslateProvider.translations('ru', {
            USERS: 'Пользователи',
            ADMINISTRATION_USERS: 'Пользователи',
            NEW_ACCOUNT: 'Новые пользователи',
            USERS_EMPTY: 'Пользователи не найдены',
            ADD_USER: 'Пригласить пользователей',
            USER_SESSIONS_EMPTY: 'Сессии не найдены',
            LOADING_PROGRESS_USER_SESSIONS: 'Загрузка сессий',
            USER_ACTIVITES_EMPTY: 'Активность не найдена',
            LOADING_PROGRESS_USER_ACTIVITES: 'Загрузка активности пользователя',
            SETTING_SYSTEM_ACCOUNTS_ROLE: 'Уровень доступа',
            SETTING_SYSTEM_ACCOUNTS_ABOUT: 'Должность',
            SETTINGS_SYSTEM_ACCOUNTS_INVITE: 'Приглашение',
            SETTING_SYSTEM_ACCOUNTS_INVITE_TITLE: 'Приглашение пользователя',
            SETTING_SYSTEM_ACCOUNTS_INVITE_TITLE_RESPONSE: 'Запрос на получение доступа',
            SETTING_SYSTEM_ACCOUNTS_INVITE_EMAIL: 'Адрес эл. почты',
            SETTING_SYSTEM_ACCOUNTS_INVITE_TIME: 'Дата последнего приглашения',
            SETTING_SYSTEM_ACCOUNTS_ADD: 'Добавить',
            RESEND: 'Повторить',
            DELETE_INVITE: 'Удалить приглашение',
            ACTIVATE_INVITE: 'Подтвердить запрос',
            DELETE_ROLE: 'Запретить доступ',
            SETTINGS_SYSTEM_ACCOUNTS_INVITE_RESPONSE: 'Запрос',
            REFUSE: 'Отказать',
            ACTIVATE: 'Принять',
            SETTING_SYSTEM_ACCOUNTS_INVITE_RESPONSE_FROM: 'Запрос от ',
            admin: 'Администратор',
            manager: 'Менеджер',
            user: 'Пользователь',
            ADMIN_SUBTITLE: 'Абсолютный доступ включая администрирование и контроль пользователей',
            MANAGER_SUBTITLE: 'Доступ ко всем функциям и настройкам системы',
            USER_SUBTITLE: 'Ограниченный доступ без изменения настроек',
            ACTIONS: 'Дейстивия',
            SESSIONS: 'Сессии',
            SETTING_SYSTEM_ACCOUNTS_SEND: 'Отправить',
            INVITE_IS_FOUND1: 'Пользователь',
            INVITE_IS_FOUND: 'Пользователь уже существует.',
            INVITE_IS_FOUND2: 'уже существует.',
            ACCOUTNT_DELETE: 'Удалить',
            USER_ID: 'Системный идентификатор',
            'SETTINGS_BASIC_INFO_FROM': 'Начиная с',
            'SETTINGS_ACTIVE_SESSIONS_CLOSE_SESSION': 'Закрыть сессию',
            'SETTINGS_ACTIVE_SESSIONS_CLOSE_ACTIVE_SESSIONS': 'Закрыть активные сессии',
            'SETTINGS_ACTIVE_SESSION_OS': 'ОС: ',
            'SETTINGS_ACTIVE_SESSION_IP': 'IP: ',
            'SETTINGS_ACTIVE_SESSION_ACTIVE': 'Активно',
            'SETTINGS_ACTIVE_SESSION_INACTIVE': 'Не активно',
            LOADING_ACCOUNTS: 'Загрузка аккаунтов...',
            ADMINISTRATION_USERS_DETAILS: 'Пользователь',
            ADMINISTRATION_USERS_EDIT: 'Редактирование',
            ADMINISTRATION_USERS_ADD: 'Добавить пользователя',
            'INFORMATION': "Информация",

        });
    }

    angular
        .module('iqsConfigUsers')
        .config(declareUsersResources);
}
